# Site settings
title: Sitzfleisch
#email: your-email@domain.com
#description: "This is a Phd journal."
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext

disqus:
    shortname: pviotti

#theme: minima
plugins:
  - jekyll-feed
